# Generated by Django 3.1.6 on 2021-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'Quantity', 'verbose_name_plural': 'Quantities'},
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
