# Generated by Django 3.1.6 on 2021-02-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210207_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
    ]
