# Generated by Django 3.1.6 on 2021-02-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210211_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productImages')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item_images', to='products.productitem')),
            ],
        ),
    ]
